name: CI with Jenkins

on:
  # Triggers the workflow on push events but only for the poc-sss branch
  push:    
    branches: [ poc-sss ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      # Trigger on-premises Jenkins to run the CI/CD pipelines
      - name: Trigger on-premises Jenkins build
        env:
          urlOfJenkinsServer: ${{ secrets.JENKINS_SERVER }} # URL of the jenkins server
          jenkinsJobName: "Swagger-PetStore" # The name of the jenkins job to run
          userName: ${{ secrets.JENKINS_USERNAME }} # user name for accessing jenkins
          password: ${{ secrets.JENKINS_PAT }} # personal Access token for accessing Jenkins
        run: |
          #Generate Crumb value
          CRUMB=`curl -s -u "$userName:$password" $urlOfJenkinsServer'/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'`
          TriggerResponse=$(curl -I -s -X POST -u "$userName:$password" -H "$CRUMB" "$urlOfJenkinsServer"/job/"$jenkinsJobName"/buildWithParameters)

          echo $TriggerResponse
